### ISSUE TITLE
Infografía Realidad aumentada, virtual y mixta - Diego Alexis Carlos Cruz

### ISSUE THREAD

**Issue by DiegoSCP117** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-DiegoSCP117#1]
[Realidad Aumentada, Virtual y Mixta - Diego Alexis Carlos Cruz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-DiegoSCP117/files/14214067/Realidad.Aumentada.Virtual.y.Mixta.-.Diego.Alexis.Carlos.Cruz.pdf)

**Comment by magaly1311** [comment]
Excelente 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
